/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstrutaDeRepeticao;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        // loop for
        int count = 10;
        
        for(int i = 0; i <= count; i++){
            System.out.println(i);
        }
        
        int totalAlunos = 10;
        
        Scanner leitorAlunos = new Scanner(System.in);
        
        while(totalAlunos > 5){
            System.out.println("Digite o nome e idade do aluno");
            
            String nomeDoAluno = leitorAlunos.next();
            int idadeAluno = leitorAlunos.nextInt();
            
            System.out.println("O nome do aluno é: " + nomeDoAluno + " e a sua idade é: " + idadeAluno);
            
            totalAlunos = totalAlunos - 1;
        }
    }
}
